// 実際に使用されている色のみを保持
export const Navy = '#001f3f'
export const Blue = '#0074D9'
export const Green = '#2ECC40'
export const Red = '#FF4136'
export const Maroon = '#85144b'
export const Black = '#111111'
export const Gray = '#AAAAAA'
export const Silver = '#D0D0D0'
export const LightSilver = '#F8F8F8'
export const White = '#FFFFFF'
